name: Gerar APK SignalPlay TV

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Essa é a mágica original: força o GitHub a usar a versão correta do motor
      - name: Instalar Gradle Compatível
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'

      # Agora gera a versão Release (Otimizada, leve e profissional)
      - name: Construir o APK (Release)
        run: gradle assembleRelease

      # =========================================================================
      # PASSO DE ASSINATURA: Usa a chave oficial e os Secrets do seu GitHub
      # =========================================================================
      - name: Assinar APK Oficial
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Disponibilizar APK Assinado para Download
        uses: actions/upload-artifact@v4
        with:
          name: SignalPlay-TV-Oficial-Assinado
          # Pega automaticamente o arquivo carimbado gerado no passo anterior
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
